/**
 * Site-wide social share card, generated by app/opengraph-image.tsx.
 *
 * Next.js merges metadata shallowly: a page that defines its own `openGraph`
 * or `twitter` object replaces the inherited one outright, dropping the root
 * share image with it. Every page sets its own title there, so each must also
 * name an image explicitly — otherwise its links share as bare text.
 */
export const SHARE_IMAGE_ALT =
  'Smartgic Visa — Dubai business setup, company formation and UAE visa services';

export const DEFAULT_SHARE_IMAGE = {
  url: '/opengraph-image',
  width: 1200,
  height: 630,
  alt: SHARE_IMAGE_ALT,
};
